FROM node:16-alpine 

ENV VUE_APP_API_URL='http://<STRAPI_URL>/graphql'
WORKDIR /app

RUN npm install -g http-server
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

EXPOSE 8080
CMD [ "http-server", "dist" ]
#CMD [ "npm", "run", "serve" ]
