name: Node.js CI

on:
  push:
    branches: [ workflow-dev ]
  pull_request:
    branches: [ workflow-dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cat Dockerfile
    - run: npm ci
    - run: cd tests && npm i && cd ..
    - run: docker-compose up -d
    - run: sleep 30
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm test
  
  deploy:
    runs-on: ubuntu-latest

    env:
      GITHUB_ENV: ./git.env

    steps:
    - uses: actions/checkout@v2
    - run: docker build -t registry.pg3.io:5000/pg3io/dashboard:$VER . --no-cache
    
