name: Deploy and test

on:
  push:
    branches:
      - 'workflows-dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - run: sed -i -e "s/http\:\/\/<STRAPI_URL>/https:\/\/dashboard-preprod.pk3.io/" Dockerfile
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: registry.pg3.io:5000
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.pg3.io:5000/pg3io/dashboard:latest-actions
      - run: pwd && ls -Ra ..
      - run: |
            echo {"site": "https://dashboard-preprod.pg3.io", "identifier": "${{ secrets.PREPROD_USER }}", "password": "${{ secrets.PREPROD_PASSWORD }}"} > tests/cypress.env.json
      - run: npm test